[package]
name = "mixnmatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1"
lazy_static = "^1"
chrono = "^0.4"
config = "^0.10"
serde_json = "^1"
urlencoding = "^1"
roxmltree = "*"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
tokio = { version = "^1", features = ["full","rt-multi-thread"] }
futures = "*"
mysql_async = "*"
md5 = "*"
